"""Contracts for the isolated host-side qualification dependency profiles."""

from __future__ import annotations

from pathlib import Path

import pytest

from scripts.standalone_cli.wheel_tools import _LockPin, _parse_lock_pins

_ROOT = Path(__file__).resolve().parents[2]
_REQUIREMENTS = _ROOT / "packaging" / "standalone_cli" / "requirements"
_DIRECT = _REQUIREMENTS / "qualification-tools.in"
_TARGETS = (
    "linux-x64-ubuntu-22.04",
    "macos-arm64",
    "macos-x64",
    "windows-x64",
)
_POSIX_CLOSURE = frozenset(
    {
        "annotated-types",
        "anyio",
        "attrs",
        "certifi",
        "cffi",
        "click",
        "cryptography",
        "h11",
        "httpcore",
        "httpx",
        "httpx-sse",
        "idna",
        "jsonschema",
        "jsonschema-specifications",
        "mcp",
        "pycparser",
        "pydantic",
        "pydantic-core",
        "pydantic-settings",
        "pyjwt",
        "python-dotenv",
        "python-multipart",
        "referencing",
        "rpds-py",
        "sse-starlette",
        "starlette",
        "typing-extensions",
        "typing-inspection",
        "uvicorn",
    }
)
_WINDOWS_QUALIFICATION_ADDITIONS = frozenset(
    {
        "altgraph",
        "colorama",
        "iniconfig",
        "packaging",
        "pefile",
        "pluggy",
        "pygments",
        "pyinstaller",
        "pyinstaller-hooks-contrib",
        "pytest",
        "pywin32",
        "pywin32-ctypes",
        "setuptools",
    }
)
_WINDOWS_QUALIFICATION_ONLY = frozenset({"colorama", "iniconfig", "pluggy", "pytest"})
_WINDOWS_MARKER_NARROWING = frozenset(
    {
        "altgraph",
        "packaging",
        "pygments",
        "pyinstaller",
        "pyinstaller-hooks-contrib",
        "setuptools",
    }
)


def _lock(target: str) -> Path:
    return _REQUIREMENTS / f"qualification-tools-{target}.txt"


def _target_lock(target: str) -> Path:
    return _REQUIREMENTS / f"{target}.txt"


def _indexed_pins(path: Path) -> dict[str, _LockPin]:
    pins = _parse_lock_pins(path.read_text(encoding="utf-8"))
    return {pin.name: pin for pin in pins}


def test_direct_requirements_are_exact_and_host_only() -> None:
    requirements = {
        line.strip()
        for line in _DIRECT.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }

    assert requirements == {
        "mcp==1.30.0",
        "jsonschema==4.26.0",
        'pytest ; sys_platform == "win32"',
        'pyinstaller==6.22.3 ; sys_platform == "win32"',
    }


@pytest.mark.parametrize("target", _TARGETS)
def test_qualification_lock_is_complete_hash_locked_wheel_closure(
    target: str,
) -> None:
    lock = _lock(target)
    text = lock.read_text(encoding="utf-8")
    pins = _indexed_pins(lock)
    expected = _POSIX_CLOSURE
    if target == "windows-x64":
        expected |= _WINDOWS_QUALIFICATION_ADDITIONS

    assert text.splitlines().count("--only-binary :all:") == 1
    assert "--index-url" not in text
    assert "--extra-index-url" not in text
    assert set(pins) == expected
    assert all(pin.hashes for pin in pins.values())
    assert pins["mcp"].version == "1.30.0"
    assert pins["jsonschema"].version == "4.26.0"
    assert pins["anyio"].version == "4.15.1"


@pytest.mark.parametrize("target", _TARGETS)
def test_qualification_lock_exactly_reconciles_with_target_profile(
    target: str,
) -> None:
    qualification = _indexed_pins(_lock(target))
    target_profile = _indexed_pins(_target_lock(target))

    if target != "windows-x64":
        assert set(qualification) <= set(target_profile)
    else:
        assert set(qualification) - set(target_profile) == _WINDOWS_QUALIFICATION_ONLY
    for name in qualification.keys() & target_profile.keys():
        pin = qualification[name]
        target_pin = target_profile[name]
        assert pin.version == target_pin.version
        assert pin.hashes == target_pin.hashes
        if target == "windows-x64" and name in _WINDOWS_MARKER_NARROWING:
            assert pin.marker == "sys_platform == 'win32'"
            assert target_pin.marker is None
        else:
            assert pin.marker == target_pin.marker


@pytest.mark.parametrize("target", _TARGETS)
def test_qualification_lock_records_reproducible_resolution(target: str) -> None:
    header = "\n".join(_lock(target).read_text(encoding="utf-8").splitlines()[:3])

    assert "autogenerated by uv" in header
    assert "uv pip compile" in header
    assert "--python-version 3.12" in header
    assert f"--constraint packaging/standalone_cli/requirements/{target}.txt" in header
    assert "--only-binary :all:" in header
    assert "--generate-hashes" in header
