"""Managed voice worker protocol and data models for Servonaut Desktop.

This package defines the standard I/O protocol, message models, framing codec,
and error taxonomy for the out-of-process voice companion runtime.
Zero native audio dependencies.
"""

from __future__ import annotations

from .protocol import (
    MAX_FRAME_BYTES,
    VOICE_PROTOCOL_VERSION,
    ConversationErrorEvent,
    ConversationInterruptRequest,
    ConversationSignalRequest,
    ConversationStartRequest,
    ConversationStateEvent,
    ConversationStopRequest,
    ConversationStoppedEvent,
    ConversationTranscriptEvent,
    HandshakeRequest,
    HandshakeResponsePayload,
    InputCapHitEvent,
    InputCancelRequest,
    InputEndpointEvent,
    InputPartialEvent,
    InputResetBudgetRequest,
    InputStartRequest,
    InputStopRequest,
    InputStopResponsePayload,
    OutputCloseRequest,
    OutputEnqueueRequest,
    OutputSpeakRequest,
    OutputSpeakResponsePayload,
    OutputStateEvent,
    OutputStopRequest,
    OutputUtteranceBeginRequest,
    OutputUtteranceEndRequest,
    OutputUtteranceEnqueueRequest,
    PingRequest,
    ProbeRequest,
    ProbeResponsePayload,
    ShutdownRequest,
    UtteranceCompletedEvent,
    VoiceErrorCode,
    VoiceErrorPayload,
    VoiceEvent,
    VoiceMessage,
    VoiceProtocolEofError,
    VoiceProtocolError,
    VoiceRequest,
    VoiceResponse,
    WorkerErrorEvent,
    decode_voice_message,
    encode_voice_message,
    read_voice_frame,
    write_voice_frame,
)

__all__ = [
    "MAX_FRAME_BYTES",
    "VOICE_PROTOCOL_VERSION",
    "ConversationErrorEvent",
    "ConversationInterruptRequest",
    "ConversationSignalRequest",
    "ConversationStartRequest",
    "ConversationStateEvent",
    "ConversationStopRequest",
    "ConversationStoppedEvent",
    "ConversationTranscriptEvent",
    "HandshakeRequest",
    "HandshakeResponsePayload",
    "InputCapHitEvent",
    "InputCancelRequest",
    "InputEndpointEvent",
    "InputPartialEvent",
    "InputResetBudgetRequest",
    "InputStartRequest",
    "InputStopRequest",
    "InputStopResponsePayload",
    "OutputCloseRequest",
    "OutputEnqueueRequest",
    "OutputSpeakRequest",
    "OutputSpeakResponsePayload",
    "OutputStateEvent",
    "OutputStopRequest",
    "OutputUtteranceBeginRequest",
    "OutputUtteranceEndRequest",
    "OutputUtteranceEnqueueRequest",
    "PingRequest",
    "ProbeRequest",
    "ProbeResponsePayload",
    "ShutdownRequest",
    "UtteranceCompletedEvent",
    "VoiceErrorCode",
    "VoiceErrorPayload",
    "VoiceEvent",
    "VoiceMessage",
    "VoiceProtocolEofError",
    "VoiceProtocolError",
    "VoiceRequest",
    "VoiceResponse",
    "WorkerErrorEvent",
    "decode_voice_message",
    "encode_voice_message",
    "read_voice_frame",
    "write_voice_frame",
]
