"""Managed voice worker protocol and data models for Servonaut Desktop.

This package defines the standard I/O protocol, message models, framing codec,
and error taxonomy for the out-of-process voice companion runtime.
Zero native audio dependencies.
"""

from __future__ import annotations

from .protocol import (
    MAX_FRAME_BYTES,
    VOICE_PROTOCOL_VERSION,
    ConversationErrorEvent,
    ConversationInterruptRequest,
    ConversationSignalRequest,
    ConversationStartRequest,
    ConversationStateEvent,
    ConversationStopRequest,
    ConversationStoppedEvent,
    ConversationTranscriptEvent,
    HandshakeRequest,
    HandshakeResponsePayload,
    InputCapHitEvent,
    InputCancelRequest,
    InputEndpointEvent,
    InputPartialEvent,
    InputResetBudgetRequest,
    InputStartRequest,
    InputStopRequest,
    InputStopResponsePayload,
    OutputCloseRequest,
    OutputEnqueueRequest,
    OutputSpeakRequest,
    OutputSpeakResponsePayload,
    OutputStateEvent,
    OutputStopRequest,
    OutputUtteranceBeginRequest,
    OutputUtteranceEndRequest,
    OutputUtteranceEnqueueRequest,
    PingRequest,
    ProbeRequest,
    ProbeResponsePayload,
    ShutdownRequest,
    UtteranceCompletedEvent,
    VoiceErrorCode,
    VoiceErrorPayload,
    VoiceEvent,
    VoiceMessage,
    VoiceProtocolEofError,
    VoiceProtocolError,
    VoiceRequest,
    VoiceResponse,
    WorkerErrorEvent,
    decode_voice_message,
    encode_voice_message,
    read_voice_frame,
    write_voice_frame,
)
from .connection import (
    VoiceConnection,
    VoiceConnectionClosedError,
    VoiceConnectionError,
    VoiceConnectionTimeoutError,
    VoiceRemoteError,
)
from .requirements import (
    VOICE_RUNTIME_VERSION,
    compute_requirements_hash,
    get_default_requirements,
)
from .runtime import (
    VoiceRuntimeError,
    VoiceRuntimeLock,
    VoiceRuntimeLockError,
    VoiceRuntimeManager,
    VoiceRuntimeManifest,
    VoiceRuntimeState,
    VoiceRuntimeStatus,
)
from .service import (
    DesktopUtteranceSession,
    DesktopVoiceConversationService,
    DesktopVoiceInputService,
    DesktopVoiceOutputService,
    build_desktop_voice_services,
)
from .worker import VoiceWorker, run_worker

__all__ = [
    "MAX_FRAME_BYTES",
    "VOICE_PROTOCOL_VERSION",
    "VOICE_RUNTIME_VERSION",
    "ConversationErrorEvent",
    "ConversationInterruptRequest",
    "ConversationSignalRequest",
    "ConversationStartRequest",
    "ConversationStateEvent",
    "ConversationStopRequest",
    "ConversationStoppedEvent",
    "ConversationTranscriptEvent",
    "DesktopUtteranceSession",
    "DesktopVoiceConversationService",
    "DesktopVoiceInputService",
    "DesktopVoiceOutputService",
    "HandshakeRequest",
    "HandshakeResponsePayload",
    "InputCapHitEvent",
    "InputCancelRequest",
    "InputEndpointEvent",
    "InputPartialEvent",
    "InputResetBudgetRequest",
    "InputStartRequest",
    "InputStopRequest",
    "InputStopResponsePayload",
    "OutputCloseRequest",
    "OutputEnqueueRequest",
    "OutputSpeakRequest",
    "OutputSpeakResponsePayload",
    "OutputStateEvent",
    "OutputStopRequest",
    "OutputUtteranceBeginRequest",
    "OutputUtteranceEndRequest",
    "OutputUtteranceEnqueueRequest",
    "PingRequest",
    "ProbeRequest",
    "ProbeResponsePayload",
    "ShutdownRequest",
    "UtteranceCompletedEvent",
    "VoiceConnection",
    "VoiceConnectionClosedError",
    "VoiceConnectionError",
    "VoiceConnectionTimeoutError",
    "VoiceErrorCode",
    "VoiceErrorPayload",
    "VoiceEvent",
    "VoiceMessage",
    "VoiceProtocolEofError",
    "VoiceProtocolError",
    "VoiceRemoteError",
    "VoiceRequest",
    "VoiceResponse",
    "VoiceRuntimeError",
    "VoiceRuntimeLock",
    "VoiceRuntimeLockError",
    "VoiceRuntimeManager",
    "VoiceRuntimeManifest",
    "VoiceRuntimeState",
    "VoiceRuntimeStatus",
    "VoiceWorker",
    "WorkerErrorEvent",
    "build_desktop_voice_services",
    "compute_requirements_hash",
    "decode_voice_message",
    "encode_voice_message",
    "get_default_requirements",
    "read_voice_frame",
    "run_worker",
    "write_voice_frame",
]
