"""Servonaut distribution models, release manifests, and cryptographic trust policy."""

from servonaut.distribution.manifest import (
    ArtifactKind,
    ManifestError,
    ManifestSchemaError,
    ManifestSignature,
    ReleaseArtifact,
    ReleaseChannel,
    ReleaseManifest,
    SemVer,
    canonicalize_json,
    parse_semver,
)
from servonaut.distribution.trust import (
    AmbiguousArtifactError,
    ManifestDowngradeError,
    ManifestExpiredError,
    ManifestOriginError,
    ManifestSignatureError,
    ManifestTargetError,
    NoCompatibleArtifactError,
    OperatingSystemTooOldError,
    TrustPolicy,
    channels_accepted_by,
    check_downgrade,
    decode_signature_bytes,
    encode_signature_bytes,
    load_ed25519_public_key,
    normalize_arch,
    normalize_platform,
    release_trust_policy,
    resolve_target_artifact,
    sign_manifest,
    verify_manifest,
)

from servonaut.distribution.builder import (
    ManifestBuilder,
    ManifestBuilderError,
)
from servonaut.distribution.verify import (
    VerificationError,
    verify_artifact_signature,
    verify_file_sha256,
    verify_release_file,
)

__all__ = [
    "AmbiguousArtifactError",
    "ArtifactKind",
    "ManifestBuilder",
    "ManifestBuilderError",
    "ManifestDowngradeError",
    "ManifestError",
    "ManifestExpiredError",
    "ManifestOriginError",
    "ManifestSchemaError",
    "ManifestSignature",
    "ManifestSignatureError",
    "ManifestTargetError",
    "NoCompatibleArtifactError",
    "OperatingSystemTooOldError",
    "ReleaseArtifact",
    "ReleaseChannel",
    "ReleaseManifest",
    "SemVer",
    "TrustPolicy",
    "VerificationError",
    "canonicalize_json",
    "channels_accepted_by",
    "check_downgrade",
    "decode_signature_bytes",
    "encode_signature_bytes",
    "load_ed25519_public_key",
    "normalize_arch",
    "normalize_platform",
    "parse_semver",
    "release_trust_policy",
    "resolve_target_artifact",
    "sign_manifest",
    "verify_artifact_signature",
    "verify_file_sha256",
    "verify_manifest",
    "verify_release_file",
]

